###
POST http://localhost:9000/api/register HTTP/1.1
content-type: application/json

{
  "email": "hilal@gmail.com",
  "password": "secret22"
}

###
POST http://localhost:9000/api/login HTTP/1.1
content-type: application/json

{
  "email": "hilal@gmail.com",
  "password": "secret22"
}


###
GET http://localhost:9000/api/links HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJlbWFpbCI6InNlY3JldDIyIiwiZXhwIjoxNzc1NjYyNzc3LCJpYXQiOjE3NzU1NzYzNzd9.aefyOO5Zg2ooOE4gHXJkKY46wy6KeTm_QWEUuEa_SMY

###
POST http://localhost:9000/api/links HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJlbWFpbCI6InNlY3JldDIyIiwiZXhwIjoxNzc1NjY3NDI2LCJpYXQiOjE3NzU1ODEwMjZ9.iNdj78CdHALLXWktAzmXq_RbLxS60l8T9m2NoDrV5xY

{
  "original_url": "https://www.geeksforgeeks.org/system-design/system-design-url-shortening-service/"
}

###
GET http://localhost:9000/27AA8gs9kXd HTTP/1.1
content-type: application/json

###
DELETE http://localhost:9000/api/links/2 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJlbWFpbCI6InNlY3JldDIyIiwiZXhwIjoxNzc1NjY3NDI2LCJpYXQiOjE3NzU1ODEwMjZ9.iNdj78CdHALLXWktAzmXq_RbLxS60l8T9m2NoDrV5xY
