###
POST http://localhost:9000/api/register HTTP/1.1
content-type: application/json

{
  "email": "arif@gmail.com",
  "password": "secret22"
}

###
POST http://localhost:9000/api/login HTTP/1.1
Content-type: application/json

{
  "email": "arif@gmail.com",
  "password": "secret22"
}


###
GET http://localhost:9000/api/links HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZW1haWwiOiJzZWNyZXQyMiIsImV4cCI6MTc3NTYzNTI4NSwiaWF0IjoxNzc1NjM0Mzg1fQ.8XODXos3KM895gbyQYjOfTCzePcBYr6LQl_r1-cxPF4

###
POST http://localhost:9000/api/links HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZW1haWwiOiJzZWNyZXQyMiIsImV4cCI6MTc3NTYzNTI4NSwiaWF0IjoxNzc1NjM0Mzg1fQ.8XODXos3KM895gbyQYjOfTCzePcBYr6LQl_r1-cxPF4

{
  "original_url": "https://www.geeksforgeeks.org/system-design/system-design-url-shortening-service/"
}

###
GET http://localhost:9000/27AA8gs9kXd HTTP/1.1
content-type: application/json

###
DELETE http://localhost:9000/api/links/2 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJlbWFpbCI6InNlY3JldDIyIiwiZXhwIjoxNzc1NjY3NDI2LCJpYXQiOjE3NzU1ODEwMjZ9.iNdj78CdHALLXWktAzmXq_RbLxS60l8T9m2NoDrV5xY

###
POST http://localhost:9000/public/generate HTTP/1.1
content-type: application/json

{
"original_url": "https://www.geeksforgeeks.org/system-design/system-design-url-shortening-service/"
}